// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'25ec48a7cc0a61c043b64e831b412d128ffba70689ceedfba665b68568c887f6'>;
export type ExecutionHash =
  ExecutionHashBase<'7d8769ebbadd918e57c0cc9cd344af0dc72d5363c881e34d95f56cb79989139b'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Customer: {
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Payment: {
      readonly amountPaid: Numeric<10, 2>;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly note: CodecTypes['pg/text@1']['output'] | null;
      readonly paymentDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly paymentMethod: CodecTypes['pg/text@1']['output'];
      readonly saleId: CodecTypes['pg/text@1']['output'];
    };
    readonly Product: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
    };
    readonly Sale: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly customerId: CodecTypes['pg/text@1']['output'];
      readonly firstDueDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly installmentAmount: Numeric<10, 2>;
      readonly installmentCount: CodecTypes['pg/int4@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly paymentFrequency: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly saleDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
    };
    readonly WeeklyClosure: {
      readonly closedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly endDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly startDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly totalAmount: Numeric<10, 2>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Customer: {
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Payment: {
      readonly amountPaid: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly note: CodecTypes['pg/text@1']['input'] | null;
      readonly paymentDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly paymentMethod: CodecTypes['pg/text@1']['input'];
      readonly saleId: CodecTypes['pg/text@1']['input'];
    };
    readonly Product: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
    };
    readonly Sale: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly customerId: CodecTypes['pg/text@1']['input'];
      readonly firstDueDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly installmentAmount: CodecTypes['pg/numeric@1']['input'];
      readonly installmentCount: CodecTypes['pg/int4@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly paymentFrequency: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly saleDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
    };
    readonly WeeklyClosure: {
      readonly closedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly endDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly startDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly totalAmount: CodecTypes['pg/numeric@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Customer: {
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Payment: {
      readonly amountPaid: Numeric<10, 2>;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly note: CodecTypes['pg/text@1']['output'] | null;
      readonly paymentDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly paymentMethod: CodecTypes['pg/text@1']['output'];
      readonly saleId: CodecTypes['pg/text@1']['output'];
    };
    readonly Product: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
    };
    readonly Sale: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly customerId: CodecTypes['pg/text@1']['output'];
      readonly firstDueDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly installmentAmount: Numeric<10, 2>;
      readonly installmentCount: CodecTypes['pg/int4@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly paymentFrequency: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly saleDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
    };
    readonly WeeklyClosure: {
      readonly closedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly endDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly startDate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly totalAmount: Numeric<10, 2>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Customer: {
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Payment: {
      readonly amountPaid: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly note: CodecTypes['pg/text@1']['input'] | null;
      readonly paymentDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly paymentMethod: CodecTypes['pg/text@1']['input'];
      readonly saleId: CodecTypes['pg/text@1']['input'];
    };
    readonly Product: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
    };
    readonly Sale: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly customerId: CodecTypes['pg/text@1']['input'];
      readonly firstDueDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly installmentAmount: CodecTypes['pg/numeric@1']['input'];
      readonly installmentCount: CodecTypes['pg/int4@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly paymentFrequency: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly saleDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
    };
    readonly WeeklyClosure: {
      readonly closedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly endDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly startDate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly totalAmount: CodecTypes['pg/numeric@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Customer = {
    address: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    firstName: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    lastName: CodecTypes['pg/text@1']['output'];
    notes: CodecTypes['pg/text@1']['output'] | null;
    phone: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    sales: public_Sale[];
    readonly [RelationKeys]?: 'sales';
  };
  export type public_Payment = {
    amountPaid: Numeric<10, 2>;
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    note: CodecTypes['pg/text@1']['output'] | null;
    paymentDate: CodecTypes['pg/timestamp-temporal@1']['output'];
    paymentMethod: CodecTypes['pg/text@1']['output'];
    saleId: CodecTypes['pg/text@1']['output'];
    sale: public_Sale;
    readonly [RelationKeys]?: 'sale';
  };
  export type public_Product = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    stock: CodecTypes['pg/int4@1']['output'];
    sales: public_Sale[];
    readonly [RelationKeys]?: 'sales';
  };
  export type public_Sale = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    customerId: CodecTypes['pg/text@1']['output'];
    firstDueDate: CodecTypes['pg/timestamp-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    installmentAmount: Numeric<10, 2>;
    installmentCount: CodecTypes['pg/int4@1']['output'];
    notes: CodecTypes['pg/text@1']['output'] | null;
    paymentFrequency: CodecTypes['pg/text@1']['output'];
    productId: CodecTypes['pg/text@1']['output'];
    quantity: CodecTypes['pg/int4@1']['output'];
    saleDate: CodecTypes['pg/timestamp-temporal@1']['output'];
    status: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    customer: public_Customer;
    payments: public_Payment[];
    product: public_Product;
    readonly [RelationKeys]?: 'customer' | 'payments' | 'product';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_WeeklyClosure = {
    closedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    endDate: CodecTypes['pg/timestamp-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    startDate: CodecTypes['pg/timestamp-temporal@1']['output'];
    totalAmount: Numeric<10, 2>;
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Customer: Models.public_Customer;
    Payment: Models.public_Payment;
    Product: Models.public_Product;
    Sale: Models.public_Sale;
    User: Models.public_User;
    WeeklyClosure: Models.public_WeeklyClosure;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Customer: {
              columns: {
                readonly address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lastName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Payment: {
              columns: {
                readonly amountPaid: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly note: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly paymentDate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly paymentMethod: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'Efectivo'>;
                  };
                };
                readonly saleId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Payment';
                    readonly columns: readonly ['saleId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Sale';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Product: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly stock: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Sale: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly customerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly firstDueDate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly installmentAmount: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
                readonly installmentCount: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly paymentFrequency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly saleDate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDIENTE'>;
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Sale';
                    readonly columns: readonly ['customerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Customer';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Sale';
                    readonly columns: readonly ['productId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Product';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly User: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'User_email_key';
                  readonly columns: readonly ['email'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly WeeklyClosure: {
              columns: {
                readonly closedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly endDate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startDate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly totalAmount: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Customer: { readonly namespace: 'public' & NamespaceId; readonly model: 'Customer' };
    readonly Payment: { readonly namespace: 'public' & NamespaceId; readonly model: 'Payment' };
    readonly Product: { readonly namespace: 'public' & NamespaceId; readonly model: 'Product' };
    readonly Sale: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sale' };
    readonly User: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly WeeklyClosure: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'WeeklyClosure';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Customer: {
            readonly fields: {
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly sales: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sale' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['customerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Customer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly address: { readonly column: 'address' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly firstName: { readonly column: 'firstName' };
                readonly id: { readonly column: 'id' };
                readonly lastName: { readonly column: 'lastName' };
                readonly notes: { readonly column: 'notes' };
                readonly phone: { readonly column: 'phone' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Payment: {
            readonly fields: {
              readonly amountPaid: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly note: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly paymentMethod: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly saleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly sale: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sale' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['saleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Payment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly amountPaid: { readonly column: 'amountPaid' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly note: { readonly column: 'note' };
                readonly paymentDate: { readonly column: 'paymentDate' };
                readonly paymentMethod: { readonly column: 'paymentMethod' };
                readonly saleId: { readonly column: 'saleId' };
              };
            };
          };
          readonly Product: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly sales: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sale' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Product';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly stock: { readonly column: 'stock' };
              };
            };
          };
          readonly Sale: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly customerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly firstDueDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly installmentAmount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
              readonly installmentCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentFrequency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly saleDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly customer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Customer';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['customerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly payments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Payment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['saleId'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Sale';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly customerId: { readonly column: 'customerId' };
                readonly firstDueDate: { readonly column: 'firstDueDate' };
                readonly id: { readonly column: 'id' };
                readonly installmentAmount: { readonly column: 'installmentAmount' };
                readonly installmentCount: { readonly column: 'installmentCount' };
                readonly notes: { readonly column: 'notes' };
                readonly paymentFrequency: { readonly column: 'paymentFrequency' };
                readonly productId: { readonly column: 'productId' };
                readonly quantity: { readonly column: 'quantity' };
                readonly saleDate: { readonly column: 'saleDate' };
                readonly status: { readonly column: 'status' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly passwordHash: { readonly column: 'passwordHash' };
              };
            };
          };
          readonly WeeklyClosure: {
            readonly fields: {
              readonly closedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly endDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly totalAmount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'WeeklyClosure';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly closedAt: { readonly column: 'closedAt' };
                readonly endDate: { readonly column: 'endDate' };
                readonly id: { readonly column: 'id' };
                readonly startDate: { readonly column: 'startDate' };
                readonly totalAmount: { readonly column: 'totalAmount' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Customer';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updatedAt';
            readonly namespace: 'public';
            readonly table: 'Customer';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Payment';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Product';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Sale';
          };
        },
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'updatedAt';
            readonly namespace: 'public';
            readonly table: 'Sale';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'User';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'WeeklyClosure';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
